produtos/config/routes.rb
Rails.application.routes.draw do
  get "/produtos/new" => "produtos#new"
  post "/produtos" => "produtos#create"
  delete "/produtos/:id" => "produtos#destroy", as: :produto

  root "produtos#index"
resources :produtos
  post 'entregue/:id ', :to => 'produtos#entregue', :as => :entregue
  get 'amanha', :to => 'produtos#amanha'
  get 'ontem', :to => 'produtos#ontem'
  get 'hoje', :to => 'produtos#hoje'
end

produtos/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

produtos/app/models/produto.rb
class Produto < ApplicationRecord
	validates :data, :descricao, :valor, presence:  { message: ' Campo obrigatorio' }
    validates :valor, numericality: { greater_than_or_equal_to: 1, message: ' Valor tem de ser maior que 0' }
end

produtos/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

produtos/app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
	   $request_date = Date.today
    def index
		@produtos = Produto.where(data: $request_date)
	end

	def create
		@produtos = Produto.new(produto_params)
        if @produtos.save
            $request_date = @produtos.data
            redirect_to root_url
        else
          render :new
        end
    end

	def new
		@produtos = Produto.new
	end

	def destroy
		id = params[:id]
		Produto.destroy id
		redirect_to root_url
	end


    def entregue
        @Produtos = Produto.find(params[:id])
        if @Produtos.entregue == false
            @Produtos.entregue = true
            @Produtos.save
            redirect_to root_url
        end
    end

    def edit
        @produtos = Produto.find(params[:id])
    end

   def update
        @produtos = Produto.find(params[:id])
        if @produtos.update(produto_params)
            $request_date = @produtos.data
            redirect_to root_url
        else
          render :edit
        end
    end

    def show
        @produt = Produto.find(params[:id])
    end

    def amanha
        $request_date += 1.day
        redirect_to produtos_path
    end

    def ontem
        $request_date -= 1.day
        redirect_to produtos_path
    end

    def hoje
        $request_date = Date.today
        redirect_to root_url
    end


    private
        def produto_params
            params.require(:produto).permit(:data, :descricao, :valor)
        end

    
    
end

produtos/app/helpers/application_helper.rb
module ApplicationHelper
end

produtos/app/helpers/produtos_helper.rb
module ProdutosHelper
end

produtos/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produtos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

produtos/app/views/produtos/create.html.erb
criado

produtos/app/views/produtos/edit.html.erb
<%= form_for @produtos, url: {action: "update"} do |f| %>
                        <h2>Data</h2>
                        <%= f.date_field :data, as: :data, value: f.object.data %>
                        <h2>Descricao</h2>
                        <%= f.text_field :descricao %>
                        <h2>Valor</h2>
                        <%= f.number_field :valor %>
                        <%= f.submit "Editar" %>
                    <% end %>

<% if @produtos.errors.any? %>
  <p> Erros no envio das informações </p>
  <% @produtos.errors.messages.each do |c, v| %>
  <li>
    <b> <%= c%>: </b> <%= v.to_sentence %>
  </li>
  <% end %>
<% end %>

produtos/app/views/produtos/index.html.erb
<h1>Pedidos do dia <%= $request_date.try(:strftime,"%d/%m/%Y") %> </h1>


<table>
	<thead>
		<th>Data</th>
		<th>Descricao</th>
		<th>Valor</th>
        <th>Ações</th>
        <th>Entregar</th>
        <th>Editar</th>
	</thead>
	<tbody>
        <% @produtos.each do |produto| %>
            <tr>
                <td><%= produto.data.try(:strftime,"%d/%m/%Y") %></td>
                <td><%= produto.descricao %></td>
                <td><%= produto.valor %></td>
                <td><%= button_to "Excluir", produto, method: :delete, data: {confirm: "Tem certeza que deseja remover #{produto.descricao}?"} %></td>

                <% if (produto.entregue) %>
                        <td>Já foi entregue</td>
                    <% else %>
                        <td><%= button_to "Entregar", entregue_path(produto) %></td>
                <% end %>


                <td><%= link_to "Editar".html_safe, edit_produto_path(produto) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to "Criar novo pedido", produtos_new_path %><br>

<%= link_to "Dia de hoje", hoje_path %><br>

<%= link_to "Dia anterior",  ontem_path %><br>

<%= link_to "Amanhã", amanha_path %><br>

produtos/app/views/produtos/new.html.erb
<%= form_for @produtos do |f| %>

Descricao
<%= f.text_field :descricao %><br/>  

Valor
<%= f.text_area :valor %><br/>   

Data
<%= f.date_field :data %><br/>  


<%= f.submit %>
<% end %>

<%= link_to "Voltar", root_url %>


<% if @produtos.errors.any? %>
  <p> Erros no envio das informações </p>
  <% @produtos.errors.messages.each do |c, v| %>
  <li>
    <b> <%= c%>: </b> <%= v.to_sentence %>
  </li>
  <% end %>
<% end %>